[global]
        netbios name = server
        guest account = nfsnobody
        map to guest = Bad User
        workgroup = TESTWG
        security = USER

[nfs]
        comment = scratchsppace
        guest ok = Yes
        guest only = Yes
        path = /srv/nfs
        read only = No
